version: "3.8"

services:
  bot: 
    image: trol326/pidorator-bot:latest
    container_name: pidorator-bot
    deploy:
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      KEY: ${KEY}
      HOSTID: ${HOSTID}
      DBADRESS: ${DBADRESS}
      DBUSERNAME: ${DBUSERNAME}
      DBPASSWORD: ${DBPASSWORD}