name: cicd

on:
  push:
    branches:
      - main

permissions:
  issues: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.18
      - name: Code
        uses: actions/checkout@v4
      - name: Go vet
        run: go vet -x ./...
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
  approve:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Creating issue and vaiting for approve
        uses: trstringer/manual-approval@v1
        timeout-minutes: 5
        with:
          secret: ${{ github.TOKEN }}
          approvers: Trol326,trol326
          minimum-approvals: 1
          issue-body: "Deploying new bot version.\nPlease approve or deny the deployment"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: 'принять, да, подтвердить'
          additional-denied-words: 'отмена, нет, отменить'
  deploy:
    needs: approve
    runs-on: ubuntu-latest
    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v3
      with:
        webhook_url: ${{ secrets.WEBHOOK_URL }}